// Static content for the CEIJA 19 Digital Museum.
// Edit this file to update timeline events, promociones, gallery items, and team.


const ASSET_URLS = {
  creacionEscuela: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/creacionEscuela.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy9jcmVhY2lvbkVzY3VlbGEucG5nIiwiaWF0IjoxNzc4NjMxNDA5LCJleHAiOjE4MTAxNjc0MDl9.2yw7u35zrjxOk_OklV6k00AWIKhfKeWSBgPFCfEjAAA",
  primeraPromo1978: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/primeraPromo1978.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy9wcmltZXJhUHJvbW8xOTc4LnBuZyIsImlhdCI6MTc3ODYzMTQ1MywiZXhwIjoxODEwMTY3NDUzfQ.4dSmVxwY6oNYc4MdciDAgq87VC1slwZY19K2EGn6gck",
  promo1981: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/promo1981.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy9wcm9tbzE5ODEucG5nIiwiaWF0IjoxNzc4NjMxNDYyLCJleHAiOjE4MTAxNjc0NjJ9.Zm-1oxBjbn8jV4GuNSCPYYo4r0qpKNGeMPnkOrYtwjs",
  promo1980: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1980.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTgwLnBuZyIsImlhdCI6MTc3ODYzMTIxMywiZXhwIjoxODEwMTY3MjEzfQ.53Q2IieUYmrlyJHa8AWvtuoM8IPrPNlvXd9e0w__Jfc",
  promo1985: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1985.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTg1LnBuZyIsImlhdCI6MTc3ODYzMTIxOCwiZXhwIjoxODEwMTY3MjE4fQ.5VLTwdxA5VxMzCmyiEJEVaaevQ9pdpk-UTmftbntgTk",
  promo1988: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1988.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTg4LnBuZyIsImlhdCI6MTc3ODYzNDU4OSwiZXhwIjoxODEwMTcwNTg5fQ.UewLqB_gm_74bCmfPzEjx3LU5pY-vD4dKAKX4pdlv6E",
  promo1989: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1989.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTg5LnBuZyIsImlhdCI6MTc3ODYzMTIyNiwiZXhwIjoxODEwMTY3MjI2fQ.nSd8yhScsyBGunar1rNQntApBkAWn57rJFFMqJAdECw",
  promo1990: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1990.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTkwLnBuZyIsImlhdCI6MTc3ODYzMTIzMiwiZXhwIjoxODEwMTY3MjMyfQ.Jut6m4ydYcpZWvfnE7yOQEP3f311kjpSHwxu4FlUdDA",
  promo1992: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1992.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTkyLnBuZyIsImlhdCI6MTc3ODYzMTI0MCwiZXhwIjoxODEwMTY3MjQwfQ.W1HqyXiWa6aIwWi8Wtc2kWURiddipCYPj-BlBgIbzS0",
  promo1997: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1997.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTk3LnBuZyIsImlhdCI6MTc3ODYzNDU5OSwiZXhwIjoxODEwMTcwNTk5fQ.II05k8s7cmEquPajFlMJ6sf1N-V_fOMqoJb2pPFV-OI",
  promo1999: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1999.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTk5LnBuZyIsImlhdCI6MTc3ODYzMTcyMywiZXhwIjoxODEwMTY3NzIzfQ.zyR9FvL0Jzhy2yCK3gZLU-hrfRzQBXDZ4TdPHvGEGGk",
  promo2000: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2000.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDAwLnBuZyIsImlhdCI6MTc3ODYzMTI0NywiZXhwIjoxODEwMTY3MjQ3fQ.4nbVZftKYCmz4C04Y-Dhd8UwBm9xr__kJV6n05jntHc",
  promo2002: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2002.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDAyLnBuZyIsImlhdCI6MTc3ODYzMTI4MywiZXhwIjoxODEwMTY3MjgzfQ.PXaMF3Fx_BALMi6_PklnpldqcLaoptmqnBJtOY-vC5Y",
  promo2003: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2003.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDAzLnBuZyIsImlhdCI6MTc3ODYzMTMwMywiZXhwIjoxODEwMTY3MzAzfQ.CAkSfHAptHVUWR-xPC1GnkRorhpXHRk1M0Tk1VMvD0Y",
  promo2006: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2006.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDA2LnBuZyIsImlhdCI6MTc3ODYzMTMwOCwiZXhwIjoxODEwMTY3MzA4fQ.bVGg32wEO-LaZ10sBibbopn_EwgwUaT7k2WXklQoMNc",
  promo2007: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2007.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDA3LnBuZyIsImlhdCI6MTc3ODYzMTMyMCwiZXhwIjoxODEwMTY3MzIwfQ.E3hZBSMt2GZyAaDAvdE4m8URfj87pIYr3iw0LVZQVdY",
  promo2009: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2009.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDA5LnBuZyIsImlhdCI6MTc3ODYzMTMzMywiZXhwIjoxODEwMTY3MzMzfQ.G8jIPeLqpTMGU0wMVrxmmfhsOAwtWgC0hzjS1YERqTI",
  promo2019: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2019.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDE5LnBuZyIsImlhdCI6MTc3ODYzMTMzOSwiZXhwIjoxODEwMTY3MzM5fQ.9eBEmcK357FBsiAhEbaL2bE4Pf-KdrqRpv3AA_xQPDk",
  promo2021: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2021.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDIxLnBuZyIsImlhdCI6MTc3ODYzMTM0NiwiZXhwIjoxODEwMTY3MzQ2fQ.v1mdTI0fWXOCjcaN75kYIXNPB-lFz3EcS_-DW7ZBakI",
  promo2022: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2022.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDIyLnBuZyIsImlhdCI6MTc3ODYzMTM1NiwiZXhwIjoxODEwMTY3MzU2fQ.onSKVVFFDKMEvUDGHQqhAHmBvgcpNXeuTqrTEMKQEfA",
  promo2023: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2023.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDIzLnBuZyIsImlhdCI6MTc3ODYzMTM2MSwiZXhwIjoxODEwMTY3MzYxfQ.CS6OZBQBl0LBRhbMP-v7jLT3_0vEspaV78tP34JmCag",
  promo2024: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2024.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDI0LnBuZyIsImlhdCI6MTc3ODYzMTM2NywiZXhwIjoxODEwMTY3MzY3fQ.DvgAQabMMq11ByHw2-4_QZ9FzFYFv0oswGBjiTDg7kM",
  promo2025: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2025.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDI1LnBuZyIsImlhdCI6MTc3ODYzMTM3NCwiZXhwIjoxODEwMTY3Mzc0fQ.h5tPN4l_TqP1o3BkUNE2ZRSj3JRfu6sW9Qnzt6btWAk",
};

export interface TimelineEvent {
  year: string;
  date?: string;
  title: string;
  description: string;
}

export interface Promocion {
  id: string;
  year: number;
  title: string;
  imageUrl: string;
  story: string;
  graduates: string[];
}

export interface GalleryItem {
  id: string;
  type: "photo" | "video";
  src: string;
  caption: string;
  year?: string;
  location?: string;
  photographer?: string;
  story?: string;
  people?: string[];
  tags?: string[];
}

export interface TeamMember {
  id: string;
  name: string;
  role: string;
  imageUrl?: string;
}

export const TIMELINE: TimelineEvent[] = [
  {
    year: "1976",
    date: "22 de marzo de 1976",
    title: "Creación del CENS 61 en Alcira Gigena",
    description: "Inicia formalmente la actividad educativa, dependiente del CENS N° 24 de Río Cuarto. El proyecto nació para garantizar el acceso al secundario de jóvenes y adultos, impulsado por la gestión local y autoridades educativas nacionales.",
  },
  {
    year: "1980",
    title: "Traslado a la Escuela José María Paz",
    description: "A mediados de los años 80, el CENS 61 se traslada al edificio de la escuela primaria José María Paz y comienza a compartir el espacio físico en horario vespertino, modalidad que continúa hasta la actualidad.",
  },
  {
    year: "1993",
    title: "El CENS 61 pasa a ser CENMA 61",
    description: "Al transferirse del Ministerio de Educación de la Nación a la Provincia, el centro adopta el nombre de Centro Educativo de Nivel Medio para Adultos N° 61, conocido como CENMA 61.",
  },
  {
    year: "2001",
    title: "Nueva orientación de egreso",
    description: "A veinticinco años de su creación, el CENMA 61 comienza a otorgar el título de Bachilleres Orientados en Producción de Bienes y Servicios, en línea con una nueva orientación pedagógica.",
  },
  {
    year: "2001",
    date: "18 de mayo de 2001",
    title: "Creación del Anexo Elena del CENMA 61 en Alcira Gigena",
    description: "Se crea el Anexo Elena del CENMA 61 en Alcira Gigena, ampliando la presencia territorial de la institución y su impacto educativo en la región.",
  },
  {
    year: "2003",
    title: "Inicio de la Muestra Anual de Teatro",
    description: "Por iniciativa de docentes y referentes culturales del CENMA 61, comienza la Muestra Anual de Teatro. Con entrada libre y participación de estudiantes, escuelas y taller municipal, se convierte en un hito sostenido de la agenda cultural local.",
  },
  {
    year: "2005",
    title: "Creación del Anexo Río de los Sauces",
    description: "El CENMA 61 suma el Anexo Río de los Sauces y fortalece su compromiso con la educación de jóvenes y adultos en nuevas comunidades.",
  },
  {
    year: "2023",
    date: "9 de junio de 2023",
    title: "Apertura de la sede Berrotarán",
    description: "Se incorpora la sede Berrotarán al CENMA 61 Alcira Gigena, consolidando el crecimiento institucional y ampliando el alcance territorial.",
  },
  {
    year: "2023",
    title: "Participación en el Parlamento Juvenil del Mercosur",
    description: "Estudiantes del CENMA 61 participan en el Parlamento Juvenil del Mercosur en instancias local, provincial y nacional, fortaleciendo la formación ciudadana y democrática.",
  },
  {
    year: "2024",
    title: "Lanzamiento del Museo Digital",
    description: "Se presenta el Museo Digital del CENMA 61 como espacio para preservar, compartir y poner en valor la memoria institucional.",
  },
  {
    year: "2025",
    date: "16 de mayo de 2025",
    title: "Creación del Anexo Alpa Corral",
    description: "Mediante la Resolución 253 se crea el Anexo Alpa Corral del CENMA 61. Su inauguración oficial se realiza el 13 de junio de 2025, ampliando la propuesta educativa.",
  },
  {
    year: "2026",
    title: "Creación del CEIJA N° 19",
    description: "Se formaliza la creación del CEIJA N° 19 por Resolución N° 1005, consolidando un proceso histórico de crecimiento y transformación institucional.",
  },
  {
    year: "2026",
    date: "22 de marzo de 2026",
    title: "Cincuentenario: misa y árbol conmemorativo",
    description: "En acción de gracias por los 50 años de historia educativa, la comunidad del CEIJA 19 celebra una misa y realiza la plantación del Árbol del Cincuentenario.",
  },
  {
    year: "2026",
    title: "Presentación del Museo Digital del CEIJA 19",
    description: "El proyecto se presenta con la visión de innovar y conectar educación, trabajo y producción, promoviendo derechos humanos, igualdad de género, cultura de paz, preservación del ambiente y valoración de la diversidad cultural.",
  },
];

const PROMOCIONES_RAW: Promocion[] = [
  {
    id: "p1878",
    year: 1978,
    title: "Promoción 1978",
    imageUrl: ASSET_URLS.primeraPromo1978,
    story: "La primera promoción del CEIJA 19. Un grupo pequeño y unido que abrió camino para todas las que vendrían. Se reunían los sábados a estudiar en la biblioteca pública del barrio.",
    graduates: [
      "ABALOS, Elvira Fidelma",
      "BERTORELLO, Gladis Susana",
      "BERTORELLO, Nancy Estela",
      "BONETTO, Matilde",
      "CENTENO, María Ramona",
      "DANZO, Susana Mafalda",
      "FERNANDEZ, Amelia Mercedes",
      "FOLIS, María Teresa",
      "GALLUZZI, Stella Mary",
      "GARAVOGLIA, Graciela Ester",
      "LOPEZ, Angela Esther",
      "LOPEZ, Enrique Alejandro",
      "MELLANO, Norberto",
      "MINA, Catalina Magdalena",
      "MINA, Juan Carlos",
      "ROLFO, Elsa Margarita",
    ],
  },
  {
    id: "p1981",
    year: 1981,
    title: "Promoción 1981",
    imageUrl: ASSET_URLS.promo1981,
    story: "Recordada por organizar el primer viaje de egresados de la institución y por haber pintado el mural del patio central, todavía visible hoy.",
    graduates: [
      "ALVAREZ, Emma de las Mercedes",
      "BATTAGLINO, María del Carmen",
      "GALLO, Sergio Adrián",
      "GUZMÁN, Griselda Amelia",
      "MENEGUZZI, Hilda",
      "MONDINO, Shirley María",
      "RAMADÚ de FALCO, María Ana",
      "TRÍMBOLI, Eduardo Oscar",
    ],
  },
  {
    id: "p1979",
    year: 1979,
    title: "Promoción 1979",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+1979",
    story: "Segunda Promoción del Centro Educativo Nivel Secundario N° 61 CENS",
    graduates: [
      "CABRAL, Rosa Albina",
      "CARTELLIO, Ricardo Santiago",
      "DALMASSO, Edith Lucía",
      "LINGUA, Concepción del Pilar",
      "LINGUA, María Olga",
      "MENDEZ, Alicia Clelia",
      "MODOLO, Dora María",
      "NUÑEZ, Olga Isabel",
      "RODRIGUEZ, Carmen del Valle",
      "SAPORITTI, Nancy Vilma",
      "URQUIZA, Marcelo Felipe",
    ],
  },
  {
    id: "p1980",
    year: 1980,
    title: "Promoción 1980",
    imageUrl: ASSET_URLS.promo1980,
    story: "Tercera Promoción del Centro Educativo Nivel Secundario N° 61 CENS",
    graduates: [
      "ASTRADA, Alicia Haydee",
      "JUNCO, María Elena",
      "MOROSINI, Pedro José",
      "PALACIO, Héctor Hugo",
      "PERTEGARINI, Estela Beatriz",
    ],
  },
  {
    id: "p1986",
    year: 1986,
    title: "Promoción 1986",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+1986",
    story: "Novena Promoción del Centro Educativo Nivel Secundario N° 61 CENS",
    graduates: [
      "AGHEMO, Silvia Beatriz",
      "ARIAS, Gabriela Beatriz",
      "CAPELLINO, Graciela Mónica",
      "MINA, Norma Amalia",
      "PERRONE, Analía de Lourdes",
    ],
  },
  {
    id: "p1982",
    year: 1982,
    title: "Promoción 1982",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+1982",
    story: "PERITOS COMERCIALES",
    graduates: [
      "BAROCCO, Delvi Edith",
      "MARTINEZ, Olga Beatriz",
    ],
  },
  {
    id: "p1983",
    year: 1983,
    title: "Promoción 1983",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+1983",
    story: "PERITOS COMERCIALES",
    graduates: [
      "CONTI, Silvia del Valle",
      "DANIOTTI, Liliana Dominga",
      "LUCERO, Sonia Elisa",
      "MOSCONI, Graciela Antonia",
      "PAGLIARICCI, Osvaldo, Juan",
      "REYNOSO, Mirta Liliana",
      "SUAREZ, Edica Damiana",
      "VALINOTTI, Susana Mónica",
    ],
  },
  {
    id: "p1984",
    year: 1984,
    title: "Promoción 1984",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+1984",
    story: "PERITOS COMERCIALES",
    graduates: [
      "ANDINO, Rosa",
      "ARIZ, Javier Luis",
      "AVALO Mirian Beatriz",
      "BRACAMONTE, Héctor Juan",
      "CABRAL, Marta Raquel",
      "CARLE, Griselda Magdalena",
      "CARRANZA, Sara Inés",
      "CRESPO, Inés Josefina",
      "GALLO, Mirian Griselda",
      "GONZÁLEZ Irma Dora",
      "LOPEZ, Fernando Federico",
      "LUCERO, Victor Hugo",
      "MARTINEZ, Gladys Adriana",
      "MARTINEZ, Yolanda Aurora",
      "MAZZONI, Rosana del Valle",
      "ORDOÑEZ, Alicia Noemí",
      "PALACIOS, Raquel Liliana",
      "POLONI, Mirta Noemí",
      "ROST, Luis Alberto",
      "TRIMBOLI, Nélida Pascua",
      "VIGLIANCO, María Cristina",
      "VILCHE, Graciela Magdalena",
      "ZARAZAGA, Juana Inés",
    ],
  },
  {
    id: "p1985",
    year: 1985,
    title: "Promoción 1985",
    imageUrl: ASSET_URLS.promo1985,
    story: "PERITOS COMERCIALES",
    graduates: [
      "ANINO, Viviana Libertad",
      "BADELINO, Sara Beatriz",
      "BARROTTO, Elba Cristina",
      "BUSTOS, Miguel Angel",
      "CARRANZA, Claudia Beatriz",
      "CELLI, Amalia Vilma",
      "CELLI, Víctor Hugo",
      "DIAZ, Adriana Patricia",
      "FALCO, Alicia Teresa",
      "FARINA, Eduardo Enrique",
      "FUMERO, Sandra Alicia",
      "MARTÍNEZ, Adriana Edith",
      "MEDINA, Gabriel Guillermo",
      "OLIVO, Mirta Liliana",
      "RIVERO, Atilio Ismael",
      "VIALE, Alicia Yolanda",
      "VINIEGRA, Alicia de los Angeles",
    ],
  },
  {
    id: "p1987",
    year: 1987,
    title: "Promoción 1987",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+1987",
    story: "PERITOS COMERCIALES",
    graduates: [
      "AGUIRRE, María del Carmen",
      "ALTINA, Raúl Alberto",
      "BATTAGLINO, Juan Carlos",
      "CABRAL, Miguel Angel",
      "CROATTO, Ana María",
      "GARNERO, Rosa Beatriz",
    ],
  },
  {
    id: "p1988",
    year: 1988,
    title: "Promoción 1988",
    imageUrl: ASSET_URLS.promo1988,
    story: "PERITOS COMERCIALES",
    graduates: [
      "ACOSTA, Roque Salvador",
      "BAROLO, Miguel Angel",
      "BOHER, Ana Elisa",
      "FILIPPA, Jorge Juan",
      "GARCÍA, Erica Aurelia",
      "GUARINO, Celso Raúl",
      "OLIVO, Ariel René",
      "RIVAROLA, Mirta Teresa",
      "SOSA, Ana María",
      "VIALE, Patricia Marcela",
      "VIOLINO, Sergio Fabián",
      "BALDANI, Silvana Estela",
      "CUFFIA, Patricia",
      "MONTERO, Mabel del Valle",
    ],
  },
  {
    id: "p1989",
    year: 1989,
    title: "Promoción 1989",
    imageUrl: ASSET_URLS.promo1989,
    story: "PERITOS COMERCIALES",
    graduates: [
      "BUOSI, Marcela Alejandra",
      "CARDOZO, Clider Ramona",
      "FERNÁNDEZ, María Teresa",
      "GALLARDO, Sabina Mercedes",
      "GONZALEZ, Vilma Hortencia",
      "LANFRANCO, Marta Eugenia",
      "MACCIO, Olga Beatriz",
      "MONTIEL, Félix Oscar",
      "PRADO, Gustavo Adrian",
      "REYNOLDS, Adriana Mónica",
      "ROVERA, María Teresa",
      "UBERTAZZI, Mirian del Valle",
    ],
  },
  {
    id: "p1990",
    year: 1990,
    title: "Promoción 1990",
    imageUrl: ASSET_URLS.promo1990,
    story: "PERITOS COMERCIALES",
    graduates: [
      "BRIZUELA, Anita Inés",
      "CARTUCCIA, Norma Rosa",
      "CORNAGLIA, Sonia Elizabeth",
      "FENOGLIO, Rosana Beatriz",
      "FUSERO, Clemente Juan",
      "PIERONI, Carolina Cesira Pilar",
      "RAVETTA, Angel Norberto",
      "ROJO, Patricia Graciela",
      "ROSASAROLI, Patricia del Valle",
      "SEGURA, Mónica Mabel",
      "TARDIVO, Lidis Norma",
    ],
  },
  {
    id: "p1991",
    year: 1991,
    title: "Promoción 1991",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+1991",
    story: "PERITOS COMERCIALES",
    graduates: [
      "ALMIRÓN, Alida Carina",
      "ALVAREZ, Melba del Valle",
      "BULLO, Hernán Alberto",
      "CASSOLA, Mariela Silvana",
      "DANZO, Sonia Viviana",
      "GONZALEZ, Liliana Angélica",
      "MACCIO, Myrian del Valle",
      "VIALE, Sandra Liliiana",
      "OSTORERO, Victor Jorge",
      "ROJO, Rosaura Isabel",
      "ALVAREZ, Adriana María",
      "MORCINO, Juan Carlos",
      "TOTO, Rita Azucena",
    ],
  },
  {
    id: "p1992",
    year: 1992,
    title: "Promoción 1992",
    imageUrl: ASSET_URLS.promo1992,
    story: "PERITO COMERCIALES",
    graduates: [
      "DROCCO, Patricia Del Valle",
      "ESTRELLA, Juan Luis",
      "GRASSINO, Marta Isabel",
      "LUCERO, Maria cristina",
      "MARTINELLI, Mercedes Azucena",
      "MENEGUZZI, Amalia María",
      "OVIEDO, Claudia Alejandra",
      "ROJO, Susana Noemí",
      "ROMANINI, Elida Esther",
      "ROMANINI, Graciela Del Carmen",
      "TESIO, Atilio Rogelio",
    ],
  },
  {
    id: "p1993",
    year: 1993,
    title: "Promoción 1993",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+1993",
    story: "PERITO COMERCIALES",
    graduates: [
      "ARGUELLO, Elsa Nilda",
      "BECERRA, Norma Matilde",
      "BRACAMONTE, Amadeo Benjamin",
      "DANZO, José Osvaldo",
      "DI GIOVANI, Sergio Leandro",
      "GAUDINO, Claudio Martín",
      "OLIVO, Silvio Benigno",
      "OVIEDO, Norma Beatriz",
      "PISTONE, Daniel José",
      "RODRIGUEZ, Silvia Patricia",
    ],
  },
  {
    id: "p1994",
    year: 1994,
    title: "Promoción 1994",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+1994",
    story: "PERITO COMERCIALES",
    graduates: [
      "PALACIOS, Nora Miriam",
      "CEBALLE, Nelsón domingo",
      "PALACIO, Haydee Marisel",
      "ARGUELLO, Silvana Beatríz",
      "BOCCOLINI, Norma Cristina",
      "DIAZ, Elba Beatríz",
      "DOMINGUEZ, Maria Elisa",
      "FERRETTI, Analía Elizabeth",
      "OVIEDO, Marcela del Valle",
    ],
  },
  {
    id: "p1995",
    year: 1995,
    title: "Promoción 1995",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+1995",
    story: "PERITO COMERCIALES",
    graduates: [
      "CEBALLOS, Graciela Noemi",
      "ESCUDERO, Patricia Noemí",
      "MEDINA, María Alejandra",
      "MENEGUZZI, Ana María",
      "OLMEDO, Faviana Andrea",
      "PALACIO, María Olga",
      "POLONI, Claudio Rubén",
    ],
  },
  {
    id: "p1996",
    year: 1996,
    title: "Promoción 1996",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+1996",
    story: "PERITOS COMERCIALES",
    graduates: [
      "URQUIZA, María Edith",
      "CABRAL, María Isabel",
      "POLONI, Gustavo Germán",
      "DOMINGUEZ, Claudia del Carmen",
      "FISCHER, Norma Beatriz",
      "GIACHERO, Telma Haydeé",
      "GIANINETTO, Claudia Carolina",
      "HERRERA, Lidia Alcira",
      "LOZANO, Analía Raquel",
      "MARTEL, Erica Patricia",
      "MARTINI, Luis Octavio",
      "MOLINA, Juan Alberto",
      "ORDOÑEZ, Graciela Liliana",
      "OVIEDO, Manuel Luis",
      "TOSELLI, Rosa Amelia",
    ],
  },
  {
    id: "p1997",
    year: 1997,
    title: "Promoción 1997",
    imageUrl: ASSET_URLS.promo1997,
    story: "PERITOS COMERCIALES",
    graduates: [
      "POLONI, Ivana Carina",
      "RAMIREZ, Nestor luciano",
      "FOLIS, Mariela Elizabeth",
      "GOMEZ, Mariana Belén",
      "KUNZ, Adriana Noemí",
      "MARTINEZ, Cristina del Valle",
      "NIEVAS, Mariana de los Angeles",
      "ORDOÑEZ, Carina Del Valle",
      "OVIEDO, Graciela Noemí",
      "PALACIO, Alberto Daniel",
      "GALLO, Sergio Adrian",
    ],
  },
  {
    id: "p1998",
    year: 1998,
    title: "Promoción 1998",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+1998",
    story: "Promocion 1998 del CEIJA 19",
    graduates: [
      "LEDESMA, Gabriela Jessica",
      "REYNOLDS, Jorge Angel",
      "GOMEZ, Alfredo David Tadeo",
      "PALACIO, Lorena Veronica",
      "ANGHINOLFI, Juan Pablo",
      "BULLA, Claudio Dario",
      "BUOSI, Stella Maris",
      "CEBALLOS Hilda Daniela",
      "ESTRELLA, Mariana",
      "MOLINA, Haydée Ester",
      "ROMO, Adelaida Beatriz",
      "TOLEDO, Anibal Rafael",
      "OLIVO, Ulises Javier",
      "DIAZ, Sergio Martín",
      "BOGINO, Elvi Beatríz",
      "BULLA, Edgardo Alberto",
      "SCOPONI, María Fernanda",
      "ANDRADA, Fernando Ariel",
      "GUZMAN, Marcos Daniel",
      "SERGI, Nicolás",
    ],
  },
  {
    id: "p1999",
    year: 1999,
    title: "Promoción 1999",
    imageUrl: ASSET_URLS.promo1999,
    story: "Promocion 1999 del CEIJA 19",
    graduates: [
      "SOSA, Ricardo Luis",
      "URQUIZA, Marta Ofelia",
      "ALMIRON, Cecilia Luciana",
      "GUTIERREZ, Veronica Beatríz",
      "LUNA, Paola Betiana",
      "BRACAMONTE, Marcos Javier",
      "BRINGAS, Mariela Rosana",
      "DANIELE, Clyde Josefina",
      "ESTRELLA, Fernanda",
      "FERNANDEZ, Mónica Mabel",
      "FERRETTI, Estela María",
      "GILARDINI, Patricia Rafaela",
      "GONZALEZ, Miguel Angel",
      "MALANO, Silvia Maricel",
      "MARTINEZ, Gabriela Bettiana",
      "PLANO, Giselle Beatríz",
      "AUDISIO, Sonia Noemí",
      "PATOGLIO, Micaela Nadina Belén",
      "AGUIRRE, Carina Mariela",
      "ARIAS, Analia Alejandra",
      "CASTELLI, Anabella Carla",
      "MARTEL, Adriana Beatríz",
      "BELOUS, Gisela Tamara",
      "CEJAS, Rosana Gabriela",
      "DEGIORGI, Néstor Daniel",
      "LOPEZ, Sergio Rubén",
      "DARICO, Marisa de Luján",
      "LOPEZ, María Ester",
      "PEREZ, Dario Ismael",
    ],
  },
  {
    id: "p2000",
    year: 2000,
    title: "Promoción 2000",
    imageUrl: ASSET_URLS.promo2000,
    story: "PERITOS COMERCIALES",
    graduates: [
      "ACEVEDO, Daniel Horacio",
      "VIOLINO, Santiago Iván",
      "TINES, Hernan Mario",
      "MOLINA, Marcos Alberto",
      "CARABACA, Leonardo",
      "CASALDI, Fabian Ezequiel",
      "ARIAS, Julia Esther",
      "BAHL, María Lorena",
      "CAMARGO, Carina del Valle",
      "DESAMO, Rosana del Valle",
      "FORESTE, Leonardo Javier",
      "GARAY, Veronica Elizabeth",
      "ROJO, Gimena Vanina",
      "SERVINO, Esther Gladys",
      "GARNERO,Julia Teresa",
      "BOGINO, Veronica Raquel",
      "AYALA, Carina Elizabeth",
    ],
  },
  {
    id: "p2001",
    year: 2001,
    title: "Promoción 2001",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+2001",
    story: "BACHILLER ORIENTADO EN PRODUCCIÓN DE BIENES Y SERVICIOS",
    graduates: [
      "MOLINA, Vilma Andrea",
      "MASSINI, Juan Pablo",
      "FERNANDEZ, Silvana Valeria",
      "SERVINO, Paola Luján",
      "SOSA, Griselda Mariana",
      "ARGUELLO, Cristian Javier",
      "ANDRADA, Miguel Angel",
      "BAGGINI, María Elena",
      "BRICCA, Renata Georgina",
      "DEVIA, Osvaldo Fabián",
      "FERNANDEZ, Marta Raquel",
      "GARAY, Miriam Maricel",
      "LOVERA, Lucia María",
      "LUCERO, Pamela Gisela",
      "MEDINA, Liliana Beatriz",
      "OVIEDO, Cristina del Valle",
      "PONZIO, Teresa Lucia",
      "ROJO, Cristian Ezequiel",
      "SALINAS, María Marta",
      "SCARPINELLO, Rosana Carina",
      "SUAREZ, María del Carmen Ramona",
      "ZABALA, Mariana del Carmen",
      "EANDI, Patricia Edith",
      "ABATANEO, Gustavo omar",
      "LEDESMA, Marisabel",
    ],
  },
  {
    id: "p2002",
    year: 2002,
    title: "Promoción 2002",
    imageUrl: ASSET_URLS.promo2002,
    story: "Promocion 2002 del CEIJA 19",
    graduates: [
      "BARRIONUEVO, Marcelo Alejandro",
      "AVALO, María Eugenia",
      "BONETTO, Dolly Silvana",
      "DI GIVANNI, Valeria Marina",
      "FRIAS, Mariela Silvana",
      "GALLARDO, Victor Omar",
      "HERRERA, Leila Yoryina",
      "IBARRA, Laura Cecilia",
      "MAGALLANES, Cristina del Valle",
      "MOLINERO, Andrea del Valle",
      "OCANTO, Malvina del Valle",
      "REYNOLDS, Román Oscar",
      "SOSA, Eliana Edith",
      "VIANZONE, Marta America",
      "FERNANDEZ, Juan Marcelo",
      "MACCIO, Carlos Alberto",
      "CALDERON, Darío Alejandro",
    ],
  },
  {
    id: "p2003",
    year: 2003,
    title: "Promoción 2003",
    imageUrl: ASSET_URLS.promo2003,
    story: "Promocion 2003 del CEIJA 19",
    graduates: [
      "CONTRERA, María Isabel",
      "FRIAS, Ana Griselda",
      "GIORDANO, Rodolfo Juan",
      "GRASSO, Norma Beatríz",
      "MANELLI, Claudia Ester",
      "MONTIEL, Mariel Anahí",
      "OVIEDO, María del Valle",
      "PONCE, Mónica René",
      "REYNOLDS, Walter Fabián",
      "RIPA, Franco Gastón",
      "VILLAGRA, Analía del Carmen",
      "ZABALA, María Cristina",
      "GHIO, Darío Rolando",
      "GODOY, María del Pilar",
      "MARTINEZ, Valeria Edith",
      "OSTERTAG, Rosana del Valle",
      "CONTRERA, María Isabel",
      "BEJARANO, Nancy Mabel",
      "GALFRE, Mariano Javier",
    ],
  },
  {
    id: "p2004",
    year: 2004,
    title: "Promoción 2004",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+2004",
    story: "Promocion 2004 del CEIJA 19",
    graduates: [
      "MEDINA, Liliana Beatríz FOLIO 30, LIBRO 4",
      "FRIAS, Ana Griselda",
      "ARMANDO, Cecilia Haydée",
      "ARRIETA, Sonia Veronica",
      "OCANTO, Monica Patricia",
      "RIVAROLA, Celestina Elvira",
      "FREDES,José Luis",
      "GONZALEZ, Mario Nicolás",
      "MENEGUZZI, Samanta de Lourdes",
    ],
  },
  {
    id: "p2005",
    year: 2005,
    title: "Promoción 2005",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+2005",
    story: "Promocion 2005 del CEIJA 19",
    graduates: [
      "FERRERO, Mario Carlos",
      "MOYA, María Lorena",
      "ROSSI, Graciela del Carmén",
      "VOGLIOTTI, Mariana Soledad",
      "GOMEZ, Marcos Raúl Bautista",
      "GONZALEZ, Cristian David",
      "PEROTTI, Alberto Martín",
      "FALCO, Juan Alberto",
      "ROVERA, Jorge Luis",
    ],
  },
  {
    id: "p2006",
    year: 2006,
    title: "Promoción 2006",
    imageUrl: ASSET_URLS.promo2006,
    story: "ORTEGA, Mónica Deolinda (PERITO COMERCIAL)",
    graduates: [
      "CARDILE, David Ezequiel",
      "DANZO, Dante Ricardo",
      "MARTINO, Adriana Esther",
      "OLIVO, Jesica Romina",
      "PRONO, Mario Enrique",
      "TEJADA, Cristián Fabián",
      "ORDOÑEZ, Maria Eugenia",
      "URQUIZA, Pamela Vanesa",
      "ALVAREZ, Hernan Emmanuel",
      "ARRIETA, Mario Ramón",
      "LLANES, Carolina",
      "MARTINO, Adriana Esther",
      "MONDINO, Ayelen Dannae",
      "OLIVO, Jesica Romina",
    ],
  },
  {
    id: "p2007",
    year: 2007,
    title: "Promoción 2007",
    imageUrl: ASSET_URLS.promo2007,
    story: "Promocion 2007 del CEIJA 19",
    graduates: [
      "GHIGO, Sergio Oscar",
      "ARRIETA, Maria Alida",
      "BUOSI, Liliana Beatriz",
      "CANIZO, Sandra Isabel",
      "ESPINOZA OTEIZA, Benito Rafael",
      "JUNCO, Néstor Fabián",
      "MEDINA, Roxana del Valle",
      "NUÑEZ, Daniela Gisele",
      "SALGERO, Jesica Soledad",
      "SPINA, Vanesa Liria",
      "TOTO, Amilcar Mariano",
      "VIOLINO, Estefania",
      "CAMPAGNARO, Daniela Luisa",
      "LLANES, Angel Federico",
      "MORENO, Ariel Eduardo",
      "ROVERA, Maximiliano",
    ],
  },
  {
    id: "p2008",
    year: 2008,
    title: "Promoción 2008",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+2008",
    story: "Promocion 2008 del CEIJA 19",
    graduates: [
      "AVILA, Betiana Jesica Laureana",
      "DANZO, Diego Sebastián",
      "ESPINOZA, Orlando Yonatán",
      "FORESTE, Nicolás Maximiliano",
      "MORSINO, Sonia del Valle",
      "PAREDES, Rosana Beatriz",
      "CENCI, María Fernanda",
    ],
  },
  {
    id: "p2009",
    year: 2009,
    title: "Promoción 2009",
    imageUrl: ASSET_URLS.promo2009,
    story: "Promocion 2009 del CEIJA 19",
    graduates: [
      "CUELLO, Bruno Ramiro",
      "RIVERO, Mirta Liliana",
      "CESPEDES, Silvia Noemi",
      "DANZO, Emiliano Matías",
      "FABER, Franco Ariel",
      "GLORIO, Marta Beatriz",
      "LOVERA, Alicia Edit",
      "MARTINELLI, Silvia Fátima",
      "NUÑEZ, Betiana Rosana",
      "CIUFOLINI, Luz Leonela",
      "NASI, Pablo Emanuel",
    ],
  },
  {
    id: "p2010",
    year: 2010,
    title: "Promoción 2010",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+2010",
    story: "Promocion 2010 del CEIJA 19",
    graduates: [
      "MONTENEGRO, Margarita Daniela",
      "CARDETTI, Yamila de Lourdes",
      "CUCHIETTI, Mariela Véronica",
      "FERNANDEZ, Walter Javier",
      "FILIPPA, Eliana Carolina",
      "GASPERO, Blanca Graciela",
      "GILARDINI, Adriana Florencia",
      "LEDESMA, Sergio Antonio",
      "SALGERO, Alfredo Maximiliano",
      "TORRES, Valeria Alejandra",
    ],
  },
  {
    id: "p2011",
    year: 2011,
    title: "Promoción 2011",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+2011",
    story: "Promocion 2011 del CEIJA 19",
    graduates: [
      "FLORES, Gloria Silvana",
      "BOSSIO, Sandra Viviana",
      "AVILA, Maria José",
      "BUOSI, Ada Analia",
      "DE LA TORRE, Nora Lidia",
      "GONZALEZ, Marcelina",
      "LUCERO, Tania Melisa",
      "MARQUEZ DA ROSA, Ramona Itatí",
      "MENEGUZZI,Debora María",
      "MONTIEL, Pastora Ofelia",
      "PAQUIOLO, María Isabel",
      "SANCHEZ, Leonela Anahí",
      "SPINA, Andrea Marina",
      "SUAREZ, Lucrecia Anahí",
      "AGUILERA, Jesica Anahí",
      "BIGOLIN, Fernando Atilio",
      "CIRAVEGNA, María Eugenia",
      "ROJO, Luciana",
      "DOMINGUEZ",
      "GHIGLIONE, Silvina Noelia",
    ],
  },
  {
    id: "p2012",
    year: 2012,
    title: "Promoción 2012",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+2012",
    story: "Promocion 2012 del CEIJA 19",
    graduates: [
      "SCARPINELLO, María Cristina",
      "ARGUELLO, Leslie Daiana",
      "BRACAMONTE, Alexander Ismael",
      "CENTENO, Romina Laura",
      "RINCÓN, María Alejandra",
      "MONTENEGRO, Daiana Ayelen",
      "ACCENDRE, Juan Manuel",
    ],
  },
  {
    id: "p2013",
    year: 2013,
    title: "Promoción 2013",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+2013",
    story: "Promocion 2013 del CEIJA 19",
    graduates: [
      "TOLEDO, Zulma Daniela",
      "RODRIGUEZ, Yamila Tatiana",
      "CABRAL, Graciela Mercedes",
      "CORSANICO, María José",
      "SÁNCHEZ, Nicolás Exequiel",
      "YEDRO, Norma Graciela",
      "CABRERA, María Virginia",
      "CARBALLO, Raquel Noemí",
      "IRUSTA, Cecilia del Valle",
      "TOSELLI, Mateo Exequiel",
    ],
  },
  {
    id: "p2014",
    year: 2014,
    title: "Promoción 2014",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+2014",
    story: "Promocion 2014 del CEIJA 19",
    graduates: [
      "PRETTI, Franco Maximiliano",
      "ARGUELLO, Natacha Ayelén",
      "CARBONARI, Luciano Ezequiel",
      "CEJAS, Florencia Agustina",
      "FRIAS, Anahí Claudia",
      "LAURINDO, Carolina Soledad",
      "ZUÑIGA, María Carolina",
      "AGUIRRE, Walter Samuel",
      "AMIN, Sabrina Janet",
      "ALDERETE, Carla Soledad",
      "DELFINO, Valentina Ayelén",
    ],
  },
  {
    id: "p2015",
    year: 2015,
    title: "Promoción 2015",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+2015",
    story: "Promocion 2015 del CEIJA 19",
    graduates: [
      "PLEITAVINO, María Laura",
      "ARRIETA, Martín Gabriel",
      "CAMARGO, Rosana Beatríz",
      "DEGIORGI, Vanina Soledad",
      "FRIAS, María Soledad",
      "MERCADO, Juliana Soledad",
      "BAROTTO, Ismael Darío",
      "RE, Julieta del Valle",
    ],
  },
  {
    id: "p2016",
    year: 2016,
    title: "Promoción 2016",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+2016",
    story: "Promocion 2016 del CEIJA 19",
    graduates: [
      "ORDOÑEZ, Danilo Imanol",
      "ACEVEDO, Noris Esther",
      "BRITOS SOSA, Andrea Alejandra",
      "HEREDIA, Maria de los Ángeles",
      "NASI,Gisel",
      "ROJO, Paola del Valle",
      "SUAREZ, Ricardo José",
      "CARBONARI, Emiliano Andrés",
      "DOMINGUEZ, Naiara Luz",
      "TEJADA, Roberto Samuel",
      "VILLEGAS,Mateo Jesús",
    ],
  },
  {
    id: "p2017",
    year: 2017,
    title: "Promoción 2017",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+2017",
    story: "Promocion 2017 del CEIJA 19",
    graduates: [
      "MANISCOTTI, Patricia Alejandra",
      "OSTERTAG, Mayra Daiana",
      "ARZAUTE, Karen Natalia",
      "CASSOLA, Gladys María",
      "DIAZ, Silvina Lorena",
      "AVALOS, Cindy del Rosario",
      "MARTINO, María Olga",
      "VILARIÑO, Ana Paula María",
      "CEBALLOS, Solange Aylén",
      "FUSERO, María Emilia",
    ],
  },
  {
    id: "p2018",
    year: 2018,
    title: "Promoción 2018",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+2018",
    story: "Promocion 2018 del CEIJA 19",
    graduates: [
      "AVALOS,Sofia Lara",
      "LUNA, Miguel Alejandro",
      "ARRIETA,Mauricio Ezequiel",
      "CORNEJO, Yamila Anabel",
      "LINGUA, Leonel Maximiliano",
      "SIROLESI, Alexis Damián",
      "ARGUELLO, María del Rosario",
      "GARNERO, María Luján",
      "DOBLA, Romina de los Ángeles",
      "RIVAROLA, Franco Agustín",
      "SOSA, Marilina del Valle",
      "ZABALA CUCCHIETTI, Brisa",
    ],
  },
  {
    id: "p2019",
    year: 2019,
    title: "Promoción 2019",
    imageUrl: ASSET_URLS.promo2019,
    story: "Promocion 2019 del CEIJA 19",
    graduates: [
      "GARCIA, Katherina Gabriela",
      "ALBARRACIN, Soledad Cristina",
      "BUFFA, Marisa del Valle",
      "MERCADO, Lucila Ayelén",
      "OVIEDO, Yamila Verónica",
      "PALOMEQUE, Aldana Soledad",
      "SERVIN, Eliana Macarena",
      "SERVIN, Mariela Carolina",
      "VILLARROEL, Deolinda Mercedes",
      "LEDESMA, Mónica Magalí",
      "LUCERO, Lautaro Joaquin",
      "NIEVAS, Sandra Viviana",
      "RAMELLO, Miguel Alejandro",
      "RIVERO, Sergio David",
      "ARGUELLO, Valentina del Rosario",
      "OCHOA, Mercedes Valentina",
      "PALANDRI, Nicolás Anselmo",
    ],
  },
  {
    id: "p2020",
    year: 2020,
    title: "Promoción 2020",
    imageUrl: "https://placehold.co/1200x800?text=Promocion+2020",
    story: "Promocion 2020 del CEIJA 19",
    graduates: [
      "ARIAS CORNEJO, Antonella Trinidad",
      "MUÑOZ, Antonella Tamara",
      "SANCHEZ, Milagros Anabela",
      "SAPORITI, Federico Eduardo",
      "LUCERO, Martín Sebastián",
      "PEREYRA, María Marta",
      "FERNANDEZ, Johana Soledad",
      "GHIGLIONE, Ignacio Martín",
      "MEDINA, María del Rosario",
      "GILARDINI, Julia Inés",
    ],
  },
  {
    id: "p2021",
    year: 2021,
    title: "Promoción 2021",
    imageUrl: ASSET_URLS.promo2021,
    story: "Promocion 2021 del CEIJA 19",
    graduates: [
      "CORSANIGO, Dahyana Nahir",
      "ORQUERA FERREYRA, Lara Naimi",
      "OSTERTAG, Nicolás Marcelo",
      "DUARTE, Patricia Alejandra",
      "OVIEDO, Leandro Germán",
      "PEREYRA, Jonathan Julian",
      "TEJADA, Micaela Noelia",
      "FARICELLI, Ariel Alejandro",
      "GOMÉZ, Jésica Anahí",
      "ANDRADA, Candela",
      "VILLAGRA, Graciela Patricia",
      "GOMEZ, Celia Alejandra",
    ],
  },
  {
    id: "p2022",
    year: 2022,
    title: "Promoción 2022",
    imageUrl: ASSET_URLS.promo2022,
    story: "Promocion 2022 del CEIJA 19",
    graduates: [
      "RASSIA, Dahyana del Pilar",
      "URQUIZA, Ana Luz",
      "CABRAL D’AMORE, Julieta Rocio",
      "CEBALLOS, Jesús Rodolfo",
      "ANDRADA, Vanesa Trinidad",
      "ARGUELLO, Jonathan Rodrigo",
      "ARGUELLO, Mariela Elizabeth",
      "BARAZA, Macarena Elizabet",
      "CARRANZA, Micaela Soledad",
      "CEBALLOS, Conrado Nahuel",
      "CEJAS, Daiana",
      "CUEVA, María Angela",
      "ETCHEVERRY, Norma Beatriz",
      "GRIFFA, Laura Verena",
    ],
  },
  {
    id: "p2023",
    year: 2023,
    title: "Promoción 2023",
    imageUrl: ASSET_URLS.promo2023,
    story: "Promocion 2023 del CEIJA 19",
    graduates: [
      "GOMEZ, Maricel Carina",
      "ORELLANO, Lucrecia Anahí",
      "HEREDIA, Carina Cristina",
    ],
  },
  {
    id: "p2024",
    year: 2024,
    title: "Promoción 2024",
    imageUrl: ASSET_URLS.promo2024,
    story: "Promocion 2024 del CEIJA 19",
    graduates: [
      "AGUIRRE, Jésica Melina",
    ],
  },
  {
    id: "p2025",
    year: 2025,
    title: "Promoción 2025",
    imageUrl: ASSET_URLS.promo2025,
    story: "Promocion 2025 del CEIJA 19",
    graduates: [
      "ORTIZ QUIROGA, Jeremias Alexander",
      "ORDOÑEZ, Sandro Javier",
      "ALMIRON, Gustavo Daniel",
      "DANZO, Daniel Oscar",
      "GONZALEZ, Rosana Ermelinda",
      "PONZONI, Mariana Alejandra",
      "SANABRIA, Sofia Ayelen",
      "FERRERO, Carlos Daniel",
    ],
  },
];

export const PROMOCIONES: Promocion[] = [...PROMOCIONES_RAW].sort((a, b) => a.year - b.year);

const GALLERY_ALBUMS: GalleryItem[] = [
  {
    id: "g1978-1",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1978-1.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTc4LTEucG5nIiwiaWF0IjoxNzc4NjMzOTI1LCJleHAiOjE4MTAxNjk5MjV9.IBn6lxblL_xahri4XaZNcM8RZIv82ua-nCGxMI58LX8",
    caption: "Album 1978 - Foto 1",
    year: "1978",
    tags: ["album", "1978"],
  },
  {
    id: "g1978-2",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1978-2.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTc4LTIucG5nIiwiaWF0IjoxNzc4NjMzOTM0LCJleHAiOjE4MTAxNjk5MzR9.xVxzwP94E6VjDQx7wZh4bofauWQTTvKHQrzd5-IaYhQ",
    caption: "Album 1978 - Foto 2",
    year: "1978",
    tags: ["album", "1978"],
  },
  {
    id: "g1978-3",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1978-3.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTc4LTMucG5nIiwiaWF0IjoxNzc4NjMzOTQ0LCJleHAiOjE4MTAxNjk5NDR9.PpbQxpqH2v7raqHTjDszTr14k5p6LmbV1k0gFEVDLFM",
    caption: "Album 1978 - Foto 3",
    year: "1978",
    tags: ["album", "1978"],
  },
  {
    id: "g1978-4",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1978-4.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTc4LTQucG5nIiwiaWF0IjoxNzc4NjMzOTUwLCJleHAiOjE4MTAxNjk5NTB9.PRSDE358i3T4s5VN4Sy1sLnnke4wcQCc2oCzJm08ooo",
    caption: "Album 1978 - Foto 4",
    year: "1978",
    tags: ["album", "1978"],
  },
  {
    id: "g1980-1",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1980-1.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTgwLTEucG5nIiwiaWF0IjoxNzc4NjMzOTY0LCJleHAiOjE4MTAxNjk5NjR9.FTFCMBiAnxlZFJp5TogFbECQ8N1lzKzJSKjmLKrTwLo",
    caption: "Album 1980 - Foto 1",
    year: "1980",
    tags: ["album", "1980"],
  },
  {
    id: "g1980-2",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1980-2.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTgwLTIucG5nIiwiaWF0IjoxNzc4NjMzOTczLCJleHAiOjE4MTAxNjk5NzN9.4QfBax_6m1SH_QRWBQIzwDgqvtKKxt2soIuyKy_Apzs",
    caption: "Album 1980 - Foto 2",
    year: "1980",
    tags: ["album", "1980"],
  },
  {
    id: "g1980-3",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1980-3.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTgwLTMucG5nIiwiaWF0IjoxNzc4NjMzOTgwLCJleHAiOjE4MTAxNjk5ODB9.XLlh3bo1ooIe_CB7Cft_DI15psUd8Wyp1zvuycn92Ig",
    caption: "Album 1980 - Foto 3",
    year: "1980",
    tags: ["album", "1980"],
  },
  {
    id: "g1981-1",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1981-1.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTgxLTEucG5nIiwiaWF0IjoxNzc4NjMzOTk0LCJleHAiOjE4MTAxNjk5OTR9.g2zrX4LZBwAfRRNKT9nHLHIfxVO15fTRzcy3uIoL-nQ",
    caption: "Album 1981 - Foto 1",
    year: "1981",
    tags: ["album", "1981"],
  },
  {
    id: "g1981-2",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1981-2.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTgxLTIucG5nIiwiaWF0IjoxNzc4NjM0MDA4LCJleHAiOjE4MTAxNzAwMDh9.bHH2DuBG8w8Br_7SsFUo75tDyrkn4woSd9f1-IgS5Co",
    caption: "Album 1981 - Foto 2",
    year: "1981",
    tags: ["album", "1981"],
  },
  {
    id: "g1981-3",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1981-3.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTgxLTMucG5nIiwiaWF0IjoxNzc4NjM0MDEzLCJleHAiOjE4MTAxNzAwMTN9._OzLD-C1CbBeHPkp6A0eZuB04zk1MwRW3c8HKTsfdM0",
    caption: "Album 1981 - Foto 3",
    year: "1981",
    tags: ["album", "1981"],
  },
  {
    id: "g1983-1",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1983-1.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTgzLTEucG5nIiwiaWF0IjoxNzc4NjM0MDQ5LCJleHAiOjE4MTAxNzAwNDl9.EO-xSQa4ZWgbbFJxRX-g7gbIIfIsmbL2jQKLhXzsdxY",
    caption: "Album 1983 - Foto 1",
    year: "1983",
    tags: ["album", "1983"],
  },
  {
    id: "g1983-2",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1983-2.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTgzLTIucG5nIiwiaWF0IjoxNzc4NjM0MDY3LCJleHAiOjE4MTAxNzAwNjd9.Y_3jqvAmZORW2m6HgMXNZooIlLEwFynpSy_VDlAceBs",
    caption: "Album 1983 - Foto 2",
    year: "1983",
    tags: ["album", "1983"],
  },
  {
    id: "g1983-3",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1983-3.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTgzLTMucG5nIiwiaWF0IjoxNzc4NjM0MDc5LCJleHAiOjE4MTAxNzAwNzl9.Tb4kyDEZnoreFQ0PpYPURDBtXmFKZJRlLvzzpXcmBa4",
    caption: "Album 1983 - Foto 3",
    year: "1983",
    tags: ["album", "1983"],
  },
  {
    id: "g1985-1",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1985-1.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTg1LTEucG5nIiwiaWF0IjoxNzc4NjM0MDg5LCJleHAiOjE4MTAxNzAwODl9.KBZmMSAifDlQmugCZrpycoiasvuP_hGMN66qo5Ppqzw",
    caption: "Album 1985 - Foto 1",
    year: "1985",
    tags: ["album", "1985"],
  },
  {
    id: "g1989-1",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1989-1.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTg5LTEucG5nIiwiaWF0IjoxNzc4NjM0MDk4LCJleHAiOjE4MTAxNzAwOTh9.3Qwx6KOhD1vOd73yCbZO2OUQlKWcYlXm2sLGFO0G0To",
    caption: "Album 1989 - Foto 1",
    year: "1989",
    tags: ["album", "1989"],
  },
  {
    id: "g1989-2",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1989-2.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTg5LTIucG5nIiwiaWF0IjoxNzc4NjM0MTA3LCJleHAiOjE4MTAxNzAxMDd9.kzTydkV0g0klza5GI3l5ESONwa-K2pjR8hphOUZWPHQ",
    caption: "Album 1989 - Foto 2",
    year: "1989",
    tags: ["album", "1989"],
  },
  {
    id: "g1989-3",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1989-3.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTg5LTMucG5nIiwiaWF0IjoxNzc4NjM0MTI0LCJleHAiOjE4MTAxNzAxMjR9.CnE-KwAckqUKP4I7vr64HJTS_0geAyCyzsGbW1ioR_M",
    caption: "Album 1989 - Foto 3",
    year: "1989",
    tags: ["album", "1989"],
  },
  {
    id: "g1990-1",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1990-1.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTkwLTEucG5nIiwiaWF0IjoxNzc4NjM0MTcwLCJleHAiOjE4MTAxNzAxNzB9.Ji9qK8pahKX2ienABVJwu69F_UCfGgYKTNvVxZIuqDk",
    caption: "Album 1990 - Foto 1",
    year: "1990",
    tags: ["album", "1990"],
  },
  {
    id: "g1990-2",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1990-2.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTkwLTIucG5nIiwiaWF0IjoxNzc4NjM0MTc2LCJleHAiOjE4MTAxNzAxNzZ9.W8iEQBNbSzPFMbhI2R22HuG5QbAzOxVy-8OrkJG-l-w",
    caption: "Album 1990 - Foto 2",
    year: "1990",
    tags: ["album", "1990"],
  },
  {
    id: "g1990-3",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1990-3.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTkwLTMucG5nIiwiaWF0IjoxNzc4NjM0MTg5LCJleHAiOjE4MTAxNzAxODl9._29Tuh5Ww4A7PCCpjjSwO8-VUxuWLPyFvFFxITDuiaQ",
    caption: "Album 1990 - Foto 3",
    year: "1990",
    tags: ["album", "1990"],
  },
  {
    id: "g1990-4",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1990-4.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTkwLTQucG5nIiwiaWF0IjoxNzc4NjM0MTk4LCJleHAiOjE4MTAxNzAxOTh9.0yyr6qTp9XmjbHIiRvimHT4zZn6rKQ45Kjv4p1p1S4w",
    caption: "Album 1990 - Foto 4",
    year: "1990",
    tags: ["album", "1990"],
  },
  {
    id: "g1992-1",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/1992-1.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8xOTkyLTEucG5nIiwiaWF0IjoxNzc4NjM0MjA1LCJleHAiOjE4MTAxNzAyMDV9.VKyk7HpkVBntg4Ecgxw_xhKzAq-unDMpAuvoBECCXh0",
    caption: "Album 1992 - Foto 1",
    year: "1992",
    tags: ["album", "1992"],
  },
  {
    id: "g2002-1",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2002-1.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDAyLTEucG5nIiwiaWF0IjoxNzc4NjM0MjE5LCJleHAiOjE4MTAxNzAyMTl9.ZITl13EB1GFlBT2giQXkBeglmx2uQogSjozrhAp5UHM",
    caption: "Album 2002 - Foto 1",
    year: "2002",
    tags: ["album", "2002"],
  },
  {
    id: "g2002-2",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2002-2.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDAyLTIucG5nIiwiaWF0IjoxNzc4NjM0MjQ4LCJleHAiOjE4MTAxNzAyNDh9.nfMXTN6qqG9bNAK3AcyRS-16DF6gvDbIdfD-mbJxn2A",
    caption: "Album 2002 - Foto 2",
    year: "2002",
    tags: ["album", "2002"],
  },
  {
    id: "g2002-3",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2002-3.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDAyLTMucG5nIiwiaWF0IjoxNzc4NjM0MjU0LCJleHAiOjE4MTAxNzAyNTR9.IZE22iEZLcs-fqSuIVqS4WBwd83oTM33pbPVFMyXZEs",
    caption: "Album 2002 - Foto 3",
    year: "2002",
    tags: ["album", "2002"],
  },
  {
    id: "g2003-1",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2003-1.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDAzLTEucG5nIiwiaWF0IjoxNzc4NjM0MjYxLCJleHAiOjE4MTAxNzAyNjF9.GcCBsKtUGhB9cPepb3zH-KHB9wwFzhMkCst2yxMSenY",
    caption: "Album 2003 - Foto 1",
    year: "2003",
    tags: ["album", "2003"],
  },
  {
    id: "g2003-2",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2003-2.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDAzLTIucG5nIiwiaWF0IjoxNzc4NjM0MjY5LCJleHAiOjE4MTAxNzAyNjl9.LjPwor7oRptCI90GS3EMcqyo64IFR1N9QowMCjWcy34",
    caption: "Album 2003 - Foto 2",
    year: "2003",
    tags: ["album", "2003"],
  },
  {
    id: "g2003-3",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2003-3.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDAzLTMucG5nIiwiaWF0IjoxNzc4NjM0MzA5LCJleHAiOjE4MTAxNzAzMDl9.7px_a_q5jxG8teDddgZPeQ4dqOxQenBsQpNQUskWb9s",
    caption: "Album 2003 - Foto 3",
    year: "2003",
    tags: ["album", "2003"],
  },
  {
    id: "g2003-4",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2003-4.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDAzLTQucG5nIiwiaWF0IjoxNzc4NjM0MzI0LCJleHAiOjE4MTAxNzAzMjR9.na20tlmaWwwlDGTRdlXIU0rEptQCuXTNmfipjCacN2Y",
    caption: "Album 2003 - Foto 4",
    year: "2003",
    tags: ["album", "2003"],
  },
  {
    id: "g2007-1",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2007-1.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDA3LTEucG5nIiwiaWF0IjoxNzc4NjM0MzQwLCJleHAiOjE4MTAxNzAzNDB9.xslU-FaelGklmHIZ3wa6RkxYbqiowFWR6S37k45yza8",
    caption: "Album 2007 - Foto 1",
    year: "2007",
    tags: ["album", "2007"],
  },
  {
    id: "g2007-2",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2007-2.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDA3LTIucG5nIiwiaWF0IjoxNzc4NjM0MzQ3LCJleHAiOjE4MTAxNzAzNDd9.WG1EbeOF4WumMgYamtwbPUxaOdqetTprGcmknZSWToE",
    caption: "Album 2007 - Foto 2",
    year: "2007",
    tags: ["album", "2007"],
  },
  {
    id: "g2009-1",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2009-1.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDA5LTEucG5nIiwiaWF0IjoxNzc4NjM0MzYxLCJleHAiOjE4MTAxNzAzNjF9.c-GFMibWfqjGHkQ-BLd4D-WsyXQiWajtQ2z3bss6HRk",
    caption: "Album 2009 - Foto 1",
    year: "2009",
    tags: ["album", "2009"],
  },
  {
    id: "g2009-2",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2009-2.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDA5LTIucG5nIiwiaWF0IjoxNzc4NjM0Mzg2LCJleHAiOjE4MTAxNzAzODZ9.tn-NLEKLjfh0e6Nwc3-ajClMJTOhojAnCQqYrqONkWM",
    caption: "Album 2009 - Foto 2",
    year: "2009",
    tags: ["album", "2009"],
  },
  {
    id: "g2009-3",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2009-3.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDA5LTMucG5nIiwiaWF0IjoxNzc4NjM0NDAyLCJleHAiOjE4MTAxNzA0MDJ9.UA3rHUvQkNoPmL_0SF1_a5K4cjhamfJ_lKbX15ETRxA",
    caption: "Album 2009 - Foto 3",
    year: "2009",
    tags: ["album", "2009"],
  },
  {
    id: "g2009-4",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2009-4.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDA5LTQucG5nIiwiaWF0IjoxNzc4NjM0NDA4LCJleHAiOjE4MTAxNzA0MDh9.FBmw_SMjdy0Ztjb8CsW2YcWjuJeM9GmvpA5isNGgU1U",
    caption: "Album 2009 - Foto 4",
    year: "2009",
    tags: ["album", "2009"],
  },
  {
    id: "g2010-1",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2010-1.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDEwLTEucG5nIiwiaWF0IjoxNzc4NjM0NDE1LCJleHAiOjE4MTAxNzA0MTV9.BeF1kQqjV68jb7TZnewmJG1ew54INkXj0d7MBISbMws",
    caption: "Album 2010 - Foto 1",
    year: "2010",
    tags: ["album", "2010"],
  },
  {
    id: "g2010-2",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2010-2.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDEwLTIucG5nIiwiaWF0IjoxNzc4NjM0NDIxLCJleHAiOjE4MTAxNzA0MjF9.QiKHR3Sf6KI2r9hvPRu1frgWFiEQRdVeercf7pDe44Q",
    caption: "Album 2010 - Foto 2",
    year: "2010",
    tags: ["album", "2010"],
  },
  {
    id: "g2010-3",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2010-3.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDEwLTMucG5nIiwiaWF0IjoxNzc4NjM0NDI4LCJleHAiOjE4MTAxNzA0Mjh9.bYoPZXJPbQWbpwjk8ampoyhCrJX3aM-HwWebKLaWhv0",
    caption: "Album 2010 - Foto 3",
    year: "2010",
    tags: ["album", "2010"],
  },
  {
    id: "g2010-4",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2010-4.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDEwLTQucG5nIiwiaWF0IjoxNzc4NjM0NDYyLCJleHAiOjE4MTAxNzA0NjJ9.tRmH-zG3PCkmnEyPtAIl_PzTklYlToLaWJoRCTBXfdA",
    caption: "Album 2010 - Foto 4",
    year: "2010",
    tags: ["album", "2010"],
  },
  {
    id: "g2019-1",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2019-1.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDE5LTEucG5nIiwiaWF0IjoxNzc4NjM0NDY4LCJleHAiOjE4MTAxNzA0Njh9.o3ERhXvUSA2OAO6CJwIbIVej7_yJ7xX4ULwVmH4kIIA",
    caption: "Album 2019 - Foto 1",
    year: "2019",
    tags: ["album", "2019"],
  },
  {
    id: "g2019-2",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2019-2.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDE5LTIucG5nIiwiaWF0IjoxNzc4NjM0NDczLCJleHAiOjE4MTAxNzA0NzN9.JOm8yh7UAjtu1gCSKJ2UtGK--tYoYErzLAjiQkmk3w8",
    caption: "Album 2019 - Foto 2",
    year: "2019",
    tags: ["album", "2019"],
  },
  {
    id: "g2019-3",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2019-3.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDE5LTMucG5nIiwiaWF0IjoxNzc4NjM0NDc5LCJleHAiOjE4MTAxNzA0Nzl9.zzHQJpvRb8MzNNR76ZfQ3wojlY3BCdE_udIy6puojPM",
    caption: "Album 2019 - Foto 3",
    year: "2019",
    tags: ["album", "2019"],
  },
  {
    id: "g2019-4",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2019-4.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDE5LTQucG5nIiwiaWF0IjoxNzc4NjM0NDg1LCJleHAiOjE4MTAxNzA0ODV9.GMExf3L4gaSp0j_ExNMxR9rSPIagR_iTjR54KZNDDWQ",
    caption: "Album 2019 - Foto 4",
    year: "2019",
    tags: ["album", "2019"],
  },
  {
    id: "g2021-1",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2021-1.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDIxLTEucG5nIiwiaWF0IjoxNzc4NjM0NDkxLCJleHAiOjE4MTAxNzA0OTF9._o4tHic5ATzHY5Y8ZGcCa2xc35ObE57Uf1YBwIL9KgQ",
    caption: "Album 2021 - Foto 1",
    year: "2021",
    tags: ["album", "2021"],
  },
  {
    id: "g2022-2",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2022-2.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDIyLTIucG5nIiwiaWF0IjoxNzc4NjM0NDk4LCJleHAiOjE4MTAxNzA0OTh9.JNPVlfb6nhW0sW5Yh0X0-iFv3pnecqZIAdHmqCDf0-U",
    caption: "Album 2022 - Foto 2",
    year: "2022",
    tags: ["album", "2022"],
  },
  {
    id: "g2023-1",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2023-1.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDIzLTEucG5nIiwiaWF0IjoxNzc4NjM0NTEzLCJleHAiOjE4MTAxNzA1MTN9.mZL9pF-ouNU40jZ4Y2ZWX9leMVcsqA1oL2RspgesYOI",
    caption: "Album 2023 - Foto 1",
    year: "2023",
    tags: ["album", "2023"],
  },
  {
    id: "g2023-2",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2023-2.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDIzLTIucG5nIiwiaWF0IjoxNzc4NjM0NTIzLCJleHAiOjE4MTAxNzA1MjN9.KadVr-kANH4EkT-yF2RAAnv5WQlDC6YIrmGj93Hs3Tk",
    caption: "Album 2023 - Foto 2",
    year: "2023",
    tags: ["album", "2023"],
  },
  {
    id: "g2024-1",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2024-1.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDI0LTEucG5nIiwiaWF0IjoxNzc4NjM0NTI5LCJleHAiOjE4MTAxNzA1Mjl9.wuJQqqgwHs-bSPMshkxDcQxDqOWZbt1tUGtvU4Ekg3U",
    caption: "Album 2024 - Foto 1",
    year: "2024",
    tags: ["album", "2024"],
  },
  {
    id: "g2024-2",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2024-2.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDI0LTIucG5nIiwiaWF0IjoxNzc4NjM0NTM3LCJleHAiOjE4MTAxNzA1Mzd9.wo3FdJ0zah07JHnmB5f6wfnon6GDVKjZHwmzYDGNbd8",
    caption: "Album 2024 - Foto 2",
    year: "2024",
    tags: ["album", "2024"],
  },
  {
    id: "g2024-3",
    type: "photo",
    src: "https://aunqipledzdrzukqyoov.supabase.co/storage/v1/object/sign/Ceija%20Fotos/2024-3.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iODA0NmJkMi1hZTU3LTRmNGQtYjMyYy0wN2YxMDgzMTY4YTQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJDZWlqYSBGb3Rvcy8yMDI0LTMucG5nIiwiaWF0IjoxNzc4NjM0NTQ4LCJleHAiOjE4MTAxNzA1NDh9.G6oECHiUXohJE0swgjxnWzMV5uYL8UrJzVIxJbnofPw",
    caption: "Album 2024 - Foto 3",
    year: "2024",
    tags: ["album", "2024"],
  },
];

export const GALLERY: GalleryItem[] = [
  {
    id: "g1", type: "photo",
    src: ASSET_URLS.creacionEscuela,
    caption: "Creación de la escuela", year: "1976",
    location: "",
    photographer: "Archivo institucional CEIJA 19",
    story: "Foto de los Orígenes de la Escuela en 1976, con la presencia del Intendente Municipal de Alcira Francisco Josué Brarda, el Director Alfredo José y el Secretario Felipe Santiago Chiofalo y la Primera Promoción de nuestra escuela 1976 - 1978",
    people: ["ALFREDO JOSÉ", "FELIPE SANTIAGO CHIOFALO", "FRANCISCO JOSUÉ BRARDA"],
    tags: ["creacion", "1976", "equipo"],
  },
  ...GALLERY_ALBUMS,
];

export const TEAM: TeamMember[] = [
  { id: "t1", name: "María Amelia Chiofalo", role: "Directora" },
  { id: "t2", name: "Ramiro Pablo Alvarez del Río", role: "Secretario" },
  { id: "t3", name: "Laura del Valle Boccolini", role: "Preceptora Titular" },
  { id: "t4", name: "Jesica Beatriz Novas", role: "Preceptora Suplente" },
  { id: "t5", name: "Vanesa Soledad Acosta", role: "Profesora" },
  { id: "t6", name: "Andrea Beatriz Altina", role: "Profesora" },
  { id: "t7", name: "Paula Amalia Astegiano", role: "Profesora" },
  { id: "t8", name: "Lorena del Valle Audisio", role: "Profesora" },
  { id: "t9", name: "Victoria Barberou", role: "Profesora" },
  { id: "t10", name: "Flavia Nazarena Bigo", role: "Profesora" },
  { id: "t11", name: "María Amelia Chiofalo", role: "Profesora" },
  { id: "t12", name: "Debora Belen De la Torre", role: "Profesora" },
  { id: "t13", name: "David Osvaldo Gualtieri", role: "Profesor" },
  { id: "t14", name: "Jennifer Nerella Mondino Antunez", role: "Profesora" },
  { id: "t15", name: "Natalia Carina Oldano", role: "Profesora" },
  { id: "t16", name: "Federico Angel Strumia", role: "Profesor" },
];
