/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PromocionesRouteImport } from './routes/promociones'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as AportarRouteImport } from './routes/aportar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GaleriaIndexRouteImport } from './routes/galeria.index'
import { Route as GaleriaIdRouteImport } from './routes/galeria.$id'

const PromocionesRoute = PromocionesRouteImport.update({
  id: '/promociones',
  path: '/promociones',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const AportarRoute = AportarRouteImport.update({
  id: '/aportar',
  path: '/aportar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaIndexRoute = GaleriaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GaleriaRoute,
} as any)
const GaleriaIdRoute = GaleriaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GaleriaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aportar': typeof AportarRoute
  '/equipo': typeof EquipoRoute
  '/galeria': typeof GaleriaRouteWithChildren
  '/historia': typeof HistoriaRoute
  '/promociones': typeof PromocionesRoute
  '/galeria/$id': typeof GaleriaIdRoute
  '/galeria/': typeof GaleriaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aportar': typeof AportarRoute
  '/equipo': typeof EquipoRoute
  '/historia': typeof HistoriaRoute
  '/promociones': typeof PromocionesRoute
  '/galeria/$id': typeof GaleriaIdRoute
  '/galeria': typeof GaleriaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aportar': typeof AportarRoute
  '/equipo': typeof EquipoRoute
  '/galeria': typeof GaleriaRouteWithChildren
  '/historia': typeof HistoriaRoute
  '/promociones': typeof PromocionesRoute
  '/galeria/$id': typeof GaleriaIdRoute
  '/galeria/': typeof GaleriaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aportar'
    | '/equipo'
    | '/galeria'
    | '/historia'
    | '/promociones'
    | '/galeria/$id'
    | '/galeria/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aportar'
    | '/equipo'
    | '/historia'
    | '/promociones'
    | '/galeria/$id'
    | '/galeria'
  id:
    | '__root__'
    | '/'
    | '/aportar'
    | '/equipo'
    | '/galeria'
    | '/historia'
    | '/promociones'
    | '/galeria/$id'
    | '/galeria/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AportarRoute: typeof AportarRoute
  EquipoRoute: typeof EquipoRoute
  GaleriaRoute: typeof GaleriaRouteWithChildren
  HistoriaRoute: typeof HistoriaRoute
  PromocionesRoute: typeof PromocionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/promociones': {
      id: '/promociones'
      path: '/promociones'
      fullPath: '/promociones'
      preLoaderRoute: typeof PromocionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aportar': {
      id: '/aportar'
      path: '/aportar'
      fullPath: '/aportar'
      preLoaderRoute: typeof AportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria/': {
      id: '/galeria/'
      path: '/'
      fullPath: '/galeria/'
      preLoaderRoute: typeof GaleriaIndexRouteImport
      parentRoute: typeof GaleriaRoute
    }
    '/galeria/$id': {
      id: '/galeria/$id'
      path: '/$id'
      fullPath: '/galeria/$id'
      preLoaderRoute: typeof GaleriaIdRouteImport
      parentRoute: typeof GaleriaRoute
    }
  }
}

interface GaleriaRouteChildren {
  GaleriaIdRoute: typeof GaleriaIdRoute
  GaleriaIndexRoute: typeof GaleriaIndexRoute
}

const GaleriaRouteChildren: GaleriaRouteChildren = {
  GaleriaIdRoute: GaleriaIdRoute,
  GaleriaIndexRoute: GaleriaIndexRoute,
}

const GaleriaRouteWithChildren =
  GaleriaRoute._addFileChildren(GaleriaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AportarRoute: AportarRoute,
  EquipoRoute: EquipoRoute,
  GaleriaRoute: GaleriaRouteWithChildren,
  HistoriaRoute: HistoriaRoute,
  PromocionesRoute: PromocionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
